[project]
name = 'Decentralized-Environmental-Ocean-Plastic-Recovery'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.impact-measurement]
path = 'contracts/impact-measurement.clar'
clarity_version = 2
epoch = 2.5

[contracts.recovery-operation]
path = 'contracts/recovery-operation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
